#file: noinspection YAMLSchemaValidation
name: "Deploy to Vercel"
description: "Build artifact and publish on Vercel"

inputs:
  environment:
    description: "The environment of deployment"
    required: true
  vercel_token:
    description: "Vercel Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: web_build
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Vercel CLI
      shell: bash
      run: npm i -g vercel
    - name: Install Dependencies
      shell: bash
      run: yarn install
    - name: Vercel Deploy
      shell: bash
      run: vercel deploy --yes --prebuilt --prod --token=${{ inputs.vercel_token }}
